### ISSUE TITLE
Unable to launch the tool

### ISSUE THREAD

**Issue by rusefillc** [jnicolson/gerbmerge#8]
previous versions / other forks allow me to execute gerbmerge.py from other folders like for instance

https://github.com/rusefi/gerbmerge/blob/rusefi-tests/examples/hellen81-a/run.sh

I am not a Python power user and I am unable to launch this version:
```
rusefi@DESKTOP-57S88S8:~/gerbmerge.jnicolson$ python3 gerbmerge/gerbmerge.py
Traceback (most recent call last):
  File "gerbmerge/gerbmerge.py", line 29, in <module>
    from . import (aptable, config, drillcluster, fabdrawing, jobs, parselayout,
ImportError: attempted relative import with no known parent package
rusefi@DESKTOP-57S88S8:~/gerbmerge.jnicolson$
```

Is there a new requirement for gerbmerge.py to be located in current folder due to "from ."?

**Comment by jnicolson** [comment]
Thanks - not sure when that changed but this should fix it.  Can you pull the latest commit and try?  Let me know if there are issues

**Comment by rusefillc** [comment]
something has changed for sure but I now get total silence both with and without arguments

```
debian@debian:~/gerbmerge.jnicolson/examples/hellen81-a$ python3 ../../gerbmerge/gerbmerge.py --place-file=board_place.txt board.cfgdebian@debian:~/gerbmerge.jnicolson/examples/hellen81-a
debian@debian:~/gerbmerge.jnicolson/examples/hellen81-a$
debian@debian:~/gerbmerge.jnicolson/examples/hellen81-a$
debian@debian:~/gerbmerge.jnicolson/examples/hellen81-a$ cd ../..
debian@debian:~/gerbmerge.jnicolson$ ls- l
-bash: ls-: command not found
debian@debian:~/gerbmerge.jnicolson$ ls -l
total 84
drwxr-xr-x 3 debian debian  4096 Jan 15 23:03 doc
drwxr-xr-x 7 debian debian  4096 Jan 15 23:04 examples
drwxr-xr-x 3 debian debian  4096 Jan 15 23:03 gerbmerge
-rw-r--r-- 1 debian debian 35147 Jan 15 23:03 LICENSE
-rw-r--r-- 1 debian debian   861 Jan 15 23:03 PKG-INFO
-rw-r--r-- 1 debian debian 16410 Jan 15 23:03 README.md
-rw-r--r-- 1 debian debian   310 Jan 15 23:03 setup.py
drwxr-xr-x 2 debian debian  4096 Jan 15 23:03 testdata
drwxr-xr-x 2 debian debian  4096 Jan 15 23:03 tests
debian@debian:~/gerbmerge.jnicolson$ python3 gerbmerge/gerbmerge.py
debian@debian:~/gerbmerge.jnicolson$



```

**Comment by rusefillc** [comment]
that's latest https://github.com/jnicolson/gerbmerge with 'examples' folder from https://github.com/rusefi/gerbmerge/tree/rusefi-tests

**Comment by jnicolson** [comment]
Sorry yes I had started to refactor it to make it run as a module.  If you just run it against the folder (i.e. in your example just run:

`python3 gerbmerge`

It should run.  It still won't run your examples, I never finished refactoring to use argparse properly.  I'll push a few additional changes shortly which will get it a bit further (but still not replicating your example)

**Comment by rusefillc** [comment]
Progress I was able to launch the tool!

```
python3 ../../gerbmerge --place-file=board_place.txt board.cfg
```

Let me create other issues for other issues
